version: "3.5"

services:

  author-book-mysql:
    container_name: author-book-mysql
    image: mysql:8.0.13
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=authorbookdb
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 20s

  book-review-mongodb:
    image: mongo:4.0.3
    container_name: book-review-mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookreviewdb --quiet
      start_period: 10s
