server.port: 9080

spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/bookreviewdb
  sleuth:
    sampler.probability: 1.0

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
