management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
  health:
    binders:
      enabled: true

spring:
  jpa:
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:localhost}:3306/authordb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: secret
  sleuth:
    sampler.probability: 1.0
#    web.skipPattern: (^cleanup.*|.+favicon.*)

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

graphql: # default values
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql: # default values
  mapping: /graphiql
  endpoint: /graphql
  enabled: true