spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/authorbookdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: secret
  sleuth:
    sampler.probability: 1.0

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: basic

graphql: # default values
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql: # default values
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
    com.mycompany.authorbookapi.client.BookReviewApiClient: DEBUG